name: C programs check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile all C programs
    - run: for file in *.c; do echo "checking $file"
    gcc "$file" -o /tmp/program
    done
    
     
